# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Northern UX
email: kristoffer.darj@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Northern UX är ett community för att skapa kontakt mellan UXare i Norra Sverige.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://northernux.se" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

sass:
    sass_dir: assets/stylesheet
assets:
  sources:
    - assets
    - assets/images
    - assets/stylesheet

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
